#ifndef __SURFACE_SHADER_COMPATIBILITY_SH__
#define __SURFACE_SHADER_COMPATIBILITY_SH__

// Surface Shader source generated by pre-versioned runtimes follows ABI version 1.
#ifndef SURFACE_SHADER_ABI_VERSION
    #define SURFACE_SHADER_ABI_VERSION 1
#endif

// ABI version 1 used VERTEXCOLOR itself to signal that authored code reads COLOR.
#if SURFACE_SHADER_ABI_VERSION < 2 && defined(VERTEXCOLOR) && !defined(SURFACE_USES_COLOR)
    #define SURFACE_USES_COLOR
#endif

#if defined(SURFACE_GENERIC_OUTLINE) || defined(SURFACE_TOON_OUTLINE)
    #define _VOUTLINECOLOR , vOutlineColor
#else
    #define _VOUTLINECOLOR
#endif

#if defined(SURFACE_USES_COLOR) || defined(SURFACE_USES_VERTEX_COLOR)
    #ifdef VERTEXCOLOR
        #define GetSurfaceVertexColor() iColor
    #else
        #define GetSurfaceVertexColor() vec4(1.0, 1.0, 1.0, 1.0)
    #endif
#endif

#if defined(SURFACE_USES_COLOR) || defined(SURFACE_USES_INSTANCE_COLOR)
    #ifdef USE_INSTANCE_COLOR
        #define GetSurfaceInstanceColor() iInstanceColor
    #else
        #define GetSurfaceInstanceColor() vec4(1.0, 1.0, 1.0, 1.0)
    #endif
#endif

#ifdef SURFACE_USES_COLOR
    #ifdef USE_INSTANCE_COLOR
        #define GetSurfaceColor() (GetSurfaceVertexColor() * GetSurfaceInstanceColor())
    #else
        #define GetSurfaceColor() GetSurfaceVertexColor()
    #endif
#endif

#if defined(SURFACE_USES_COLOR) && defined(USE_INSTANCE_COLOR)
    #define DECLARE_SURFACE_COLOR_INPUTS \
        vec4 surfaceVertexColor = GetSurfaceVertexColor(); \
        vec4 surfaceInstanceColor = GetSurfaceInstanceColor(); \
        vec4 surfaceColor = surfaceVertexColor; \
        surfaceColor *= surfaceInstanceColor;
#elif defined(SURFACE_USES_COLOR) && defined(SURFACE_USES_INSTANCE_COLOR)
    #define DECLARE_SURFACE_COLOR_INPUTS \
        vec4 surfaceVertexColor = GetSurfaceVertexColor(); \
        vec4 surfaceInstanceColor = GetSurfaceInstanceColor(); \
        vec4 surfaceColor = surfaceVertexColor;
#elif defined(SURFACE_USES_COLOR)
    #define DECLARE_SURFACE_COLOR_INPUTS \
        vec4 surfaceVertexColor = GetSurfaceVertexColor(); \
        vec4 surfaceColor = surfaceVertexColor;
#elif defined(SURFACE_USES_VERTEX_COLOR) && defined(SURFACE_USES_INSTANCE_COLOR)
    #define DECLARE_SURFACE_COLOR_INPUTS \
        vec4 surfaceVertexColor = GetSurfaceVertexColor(); \
        vec4 surfaceInstanceColor = GetSurfaceInstanceColor();
#elif defined(SURFACE_USES_VERTEX_COLOR)
    #define DECLARE_SURFACE_COLOR_INPUTS \
        vec4 surfaceVertexColor = GetSurfaceVertexColor();
#elif defined(SURFACE_USES_INSTANCE_COLOR)
    #define DECLARE_SURFACE_COLOR_INPUTS \
        vec4 surfaceInstanceColor = GetSurfaceInstanceColor();
#else
    #define DECLARE_SURFACE_COLOR_INPUTS
#endif

#endif // __SURFACE_SHADER_COMPATIBILITY_SH__
